### ISSUE TITLE
Running tests with OPENAPI=1 causes all request tests to fail

### ISSUE THREAD

**Issue by xcskier56** [k0kubun/rspec-openapi#25]
Hi there,

I'm hoping to use this gem to automatically document our api, a wonderful thing. However, when I run our tests with `OPENAPI=1 rspec spec` every request spec fails with `No route matched for ....`. These tests pass when running rspec without `OPENAPI=1`.

All I have done is install the gem into the `:test` group and `bundle install`

Ideas?

**Comment by k0kubun** [comment]
Could you provide a repository that reproduces the issue?

**Comment by k0kubun** [comment]
Thank you for reporting more details. Using the engine might have something to do with the issue. 

Because I haven't seen the issue in my apps, including ones using Rails engines, I still need a repository that captures your situation, or some instructions to reproduce it from `rails new`, to give helpful advice or work on a fix. I'm sorry for the trouble, but I'd appreciate your help in reproducing it on my side.

**Comment by xcskier56** [comment]
Unfortunately I don't have enough time right now to build a repo that will reproduce, but what I found is that in this method, https://github.com/k0kubun/rspec-openapi/blob/4c6041952e478c32d5e7ee1e9745f8a5e6748a8a/lib/rspec/openapi/record_builder.rb#L65 it will be called recursively and on the first recursive call (aka 2nd call), all routes except the engine route have been removed. 

Feel free to close this. Thanks

**Comment by k0kubun** [comment]
Yeah, I think the place could be relevant to your problem. However, I cannot fix what I cannot reproduce, so please feel free to take your time and reopen this when a repository that I can take a look at is ready. Thanks.
