### ISSUE TITLE
Ideia: CI schema merger

### ISSUE THREAD

**Issue by pedrocarmona** [k0kubun/rspec-openapi#42]
Given the following steps:

A) Assuming we only generate schemas (without examples), then when running locally we could run only the files we care (where there were changes), and this would patch the existing schema (append mode).

B) In big project, one usually configures CI to run test accoss multiple nodes.
If CI would generate a swagger file each run then we need an ability to join files.
Would be nice to have cli/rake to join all files, and compile into a single file.

C) If A) and B) are addressed, then we could add a CI check to test if schema of A) matches schema of B), and fail the CI with the diff.

This would make sure our documentation is up to date - that removed routes are not present, as well as removed attributes, etc.

Wdyt?

**Comment by k0kubun** [comment]
I don't get what you're talking about in (A). It already works that way because:

> https://github.com/k0kubun/rspec-openapi#whats-this
> Furthermore, rspec-openapi keeps manual modifications when it merges automated changes to OpenAPI specs in case we can't generate everything from request specs.

If you don't like the current behavior, please file a pull request by yourself. I can't think of any other way to implement that, so I cannot write one.

---

> B) In big project, one usually configures CI to run test accoss multiple nodes.
If CI would generate a swagger file each run then we need an ability to join files.
Would be nice to have cli/rake to join all files, and compile into a single file.

It's not related to RSpec, so I want that feature to be in another gem so that the logic could be shared with other projects that don't use rspec-openapi too.

**Comment by k0kubun** [comment]
For your information, some of my colleagues seem to be using https://github.com/javanile/yamlinc for (B).

**Comment by pedrocarmona** [comment]
Hi @k0kubun, yes A) is working, sorry, It was a fast draft. 

I wanted to say: For big applications, because locally its not easy to run all tests, the append mode is the perfect solution.
However there is the case of the deleted changes, would be nice to spot them on CI.  

Inspiration for B) is (simplecov merge results)[https://github.com/simplecov-ruby/simplecov#merging-results]. 
I will take a look at yamlinc :)

Thank you for your work and response!
